### ISSUE TITLE
Any way to modify font?

### ISSUE THREAD

**Issue by Gezine** [marcussacana/LucaSystem#2]
Tried to use your SRL modified Little busters Steam version
[](https://github.com/marcussacana/Specific-Games/blob/master/Little%20Busters!%20English%20Edition.rar) 

I tried to output the Korean string
But font failed to render it
SRL built-in wordwrap did not work.

Is there any way to modify font to add other characters?

**Comment by marcussacana** [comment]
Unfortally nop, in the true my SRL isn't very stable with this engine and I lost the interest in working with this game, so I don't have anything that can help you with me.

Maybe if the garbro can read it, will be easy to create a tool to edit but i'm not looking forward to work with this game again.

**Comment by Gezine** [comment]
Thank you for your answer!
Guess there is no other way :(
Will close this issue. Thanks again :)

**Comment by Gezine** [comment]
Just an update here.....
I somehow modified FONT.PAK and it works!
Engine itself can read the PNG file. So I extracted font cz image and modified then swapped it.
But SRL is crashing 9 out of 10 when Opening movie ends.
Seems like dead end. :(

**Comment by marcussacana** [comment]
Hmm this is a cool info, But I really lost my motivation with this engine because I don't see more games using it, to me is a big lost of time if I create tool just to the Little Busters because I don't plan read it yet at least.
