### ISSUE TITLE
were you able to reverse the game executable in IDA/Ghidra ?

### ISSUE THREAD

**Issue by SeleDreams** [marcussacana/LucaSystem#4]
I am asking because when I try to reverse on ghidra for instance a lot of functions that do exist aren't actually found by the tools, I wonder if it's due to something in particular

**Comment by marcussacana** [comment]
First, You removed the steam stub?

**Comment by SeleDreams** [comment]
> First, You removed the steam stub?

I'm not really sure, tbh i'm not that used to reverse steam games

**Comment by SeleDreams** [comment]
Oh I ended up looking into it and after using the software steamless on the executable now ghidra seems to pick up the functions, i didn't know it was encrypted
